# Generated by Django 4.0.1 on 2022-03-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('collegeid', models.IntegerField(db_column='CollegeID')),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True)),
                ('phone', models.IntegerField(db_column='Phone')),
                ('passout_year', models.IntegerField(db_column='Passout_year')),
                ('experience', models.CharField(db_column='Experience', max_length=200)),
                ('current_job', models.CharField(db_column='Current_job', max_length=200)),
                ('verification_status', models.IntegerField(db_column='Verification_status')),
                ('registration_status', models.IntegerField(db_column='Registration_status')),
                ('password', models.CharField(db_column='Password', max_length=100)),
            ],
            options={
                'db_table': 'alumni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('type', models.CharField(db_column='Type', max_length=100)),
                ('city', models.CharField(db_column='City', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('password', models.CharField(db_column='Password', max_length=100)),
            ],
            options={
                'db_table': 'college',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Password', max_length=50)),
            ],
            options={
                'db_table': 'directorate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('date', models.DateField(db_column='Date')),
                ('subject', models.CharField(db_column='Subject', max_length=150)),
                ('content', models.TextField(db_column='Content')),
                ('cdid', models.IntegerField(db_column='cdID')),
            ],
            options={
                'db_table': 'email',
                'managed': False,
            },
        ),
    ]
