# Generated by Django 4.0.1 on 2022-03-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorate', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passingyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'passingyear',
                'managed': False,
            },
        ),
    ]
