# Generated by Django 4.0.1 on 2022-04-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorate', '0003_passingyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('article', models.TextField(blank=True, null=True)),
                ('heading', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'articles',
                'managed': False,
            },
        ),
    ]
